epoch_count: 5
lr: 0.001
batch_size: 128
action: "train"
grad_accum_steps: 4
log_every_n_steps: 1
check_val_every_n_epoch: 1
mlflow:
    server_uri: "http://127.0.0.1:8080"
    experiment_name: "train_1"
